window.VOLS4VETS_RESOURCES=[
  {id:'crisis',title:'Veterans Crisis Line',url:'/resources-crisis-support',description:'Call 988, then press 1, or text 838255 for veteran crisis support. If there is immediate danger, call 911.',category:'Urgent help',county:'National',state:'US',audience:'Veterans, service members, family, caregivers',tags:['crisis','urgent','mental health','suicide','988','838255'],official:true,phone:'988 then press 1',lastVerified:'2026-07-01'},
  {id:'homeless',title:'National Call Center for Homeless Veterans',url:'/resources-housing-legal',description:'Official VA starting point for veterans who are homeless or may lose housing soon.',category:'Housing',county:'National',state:'US',audience:'Veterans and helpers',tags:['housing','homeless','eviction','shelter','rent','legal'],official:true,phone:'877-424-3838',lastVerified:'2026-07-01'},
  {id:'va-benefits',title:'VA Benefits and Claims Starting Points',url:'/resources-va-benefits-healthcare',description:'Start with VA.gov, county veteran service offices or accredited representatives for claim and benefit help.',category:'VA benefits',county:'National',state:'US',audience:'Veterans, survivors, family',tags:['claim','claims','benefits','disability','DD214','records','vso'],official:true,phone:'800-827-1000',lastVerified:'2026-07-01'},
  {id:'va-health',title:'VA Health Care and Find Locations',url:'/resources-va-benefits-healthcare',description:'Official VA health care enrollment, appointments and location tools.',category:'Health care',county:'National',state:'US',audience:'Veterans',tags:['health care','clinic','VA clinic','appointments','Mountain Home'],official:true,phone:'877-222-8387',lastVerified:'2026-07-01'},
  {id:'east-tn',title:'East Tennessee Veteran Resources',url:'/resources-east-tennessee',description:'Sevier County, Knox County, Knoxville, Mountain Home VA and local starting points.',category:'Local',county:'Sevier, Knox',state:'TN',audience:'Veterans, families, caregivers',tags:['Sevier','Sevier County','Knox','Knoxville','East Tennessee','Mountain Home'],official:false,phone:'See listed offices',lastVerified:'2026-07-01'},
  {id:'jobs',title:'Veteran Jobs and Training',url:'/resources-jobs-training',description:'American Job Centers, federal hiring, resume help, apprenticeships and training options.',category:'Jobs and training',county:'Statewide',state:'TN',audience:'Veterans, service members, spouses',tags:['jobs','training','resume','federal jobs','apprenticeship','workforce'],official:true,phone:'See listed offices',lastVerified:'2026-07-01'},
  {id:'education',title:'Education and GI Bill Help',url:'/resources-education',description:'GI Bill, scholarships, certifications and school benefit starting points.',category:'Education',county:'National',state:'US',audience:'Veterans, service members, family',tags:['GI Bill','education','school','college','certification','scholarship'],official:true,phone:'888-442-4551',lastVerified:'2026-07-01'},
  {id:'family',title:'Family and Caregiver Support',url:'/resources-family-support',description:'Military OneSource, caregiver support, spouse and family resources.',category:'Family and caregivers',county:'National',state:'US',audience:'Family, caregivers, spouses, children',tags:['caregiver','family','spouse','children','Military OneSource'],official:true,phone:'800-342-9647',lastVerified:'2026-07-01'},
  {id:'women',title:'Women Veterans Resources',url:'/resources-women-veterans',description:'Women Veterans Call Center, VA women veteran health resources and support starting points.',category:'Women veterans',county:'National',state:'US',audience:'Women veterans',tags:['women veterans','women','MST','health care','call center'],official:true,phone:'855-829-6636',lastVerified:'2026-07-01'},
  {id:'state-benefits',title:'Tennessee Veteran Benefits',url:'/resources-state-benefits',description:'Tennessee Department of Veterans Services, state benefits, county offices and state programs.',category:'State benefits',county:'Statewide',state:'TN',audience:'Tennessee veterans and families',tags:['Tennessee','state benefits','county veteran service office','license plates','tax relief'],official:true,phone:'See state offices',lastVerified:'2026-07-01'},
  {id:'legal',title:'Veteran Housing and Legal Aid Starting Points',url:'/resources-housing-legal',description:'Legal Aid of East Tennessee, housing risk resources and official support options.',category:'Legal help',county:'East Tennessee',state:'TN',audience:'Veterans and families',tags:['legal','legal aid','eviction','housing','tenant','court'],official:false,phone:'See listed offices',lastVerified:'2026-07-01'},
  {id:'discounts',title:'Military Discounts and Travel',url:'/resources-travel-tickets',description:'Travel, Vet Tix and discount starting points. Confirm every offer directly before relying on it.',category:'Discounts and travel',county:'National',state:'US',audience:'Veterans, service members, family',tags:['discounts','travel','tickets','Vet Tix','Smoky Mountains','Gatlinburg','Pigeon Forge','Sevierville'],official:false,phone:'See listed programs',lastVerified:'2026-07-01'}
];
