(function(){
  var STORAGE_KEY='vols4vets_saved_action_path';
  var questions=[
    {name:'issue',label:'1. What is the main issue?',options:['Crisis or immediate danger','Homeless or may lose housing','VA benefits or disability claim','Health care or Mountain Home VA','DD214 or military records','Job, resume or training','Legal aid or court deadline','Women veteran support','Family or caregiver help','Local office or VSO help','I am not sure']},
    {name:'location',label:'2. Where are you located?',options:['Sevier County','Knox County','East Tennessee, other county','Tennessee, not East Tennessee','Outside Tennessee','I am helping someone else']},
    {name:'urgency',label:'3. How urgent is it?',options:['Immediate danger','Today','This week','This month','No deadline yet']},
    {name:'ready',label:'4. What do you already have?',options:['Photo ID','DD214','VA letters','Medical records','Court or eviction papers','Resume','Safe callback number','None of these ready'],multi:true},
    {name:'goal',label:'5. What kind of next step do you want?',options:['Call the right official office','Know what to bring','Find a local office guide','Start with an official website','Print or save a checklist']}
  ];
  var plans={
    crisis:{title:'Crisis or immediate danger path',steps:['If there is immediate danger, call 911 now.','For veteran crisis support, call 988 then press 1 or text 838255.','If safe, open the urgent help page and write down the next official contact.'],bring:['Current location','Safe callback number if available','Immediate safety concern'],official:[['Veterans Crisis Line','/resources-crisis-support'],['Call 911','tel:911']],related:[['Urgent Help','/resources-crisis-support'],['Find My Next Step','/find-my-next-step']]},
    housing:{title:'Housing risk path',steps:['If there is immediate danger, call 911.','Contact VA homeless veteran support if you are homeless or may lose housing.','Use the housing checklist and legal aid page if there is an eviction or court deadline.'],bring:['Photo ID if available','Safe callback number','Eviction or utility deadline','County and current sleeping situation'],official:[['VA homeless veteran support','https://www.va.gov/homeless/nationalcallcenter.asp'],['VA Homeless Programs','https://department.va.gov/homeless/']],related:[['Homeless veteran help','/homeless-veteran-help-east-tennessee'],['Housing Risk Action Checklist','/housing-risk-action-checklist'],['Veteran legal aid','/veteran-legal-aid-east-tennessee']]},
    claim:{title:'VA benefits or disability claim path',steps:['Start with VA.gov or an accredited representative.','Use the claim starter checklist before sharing private records.','Bring records to the official office or secure official channel, not to Vols4Vets.'],bring:['Photo ID','DD214 if available','VA letters','Written questions and deadlines'],official:[['VA disability compensation','https://www.va.gov/disability/'],['VA accredited representative search','https://www.va.gov/get-help-from-accredited-representative/find-rep/']],related:[['Tennessee VA benefits help','/tennessee-va-benefits-help'],['Start a VA disability claim','/start-va-disability-claim'],['VA Claim Starter Checklist','/va-claim-starter-checklist'],['What to bring to a VSO','/what-to-bring-vso']]},
    health:{title:'Health care or Mountain Home VA path',steps:['Use VA Find Locations to confirm the exact office or clinic.','Check service-specific appointment rules before you drive.','Use official VA channels for care questions.'],bring:['Photo ID','VA health card if you have one','Appointment details','Medication list'],official:[['Mountain Home VA location','https://www.va.gov/mountain-home-health-care/locations/james-h-quillen-department-of-veterans-affairs-medical-center/'],['VA Find Locations','https://www.va.gov/find-locations/']],related:[['Mountain Home VA guide','/mountain-home-va-guide'],['Mountain Home VA Location Checklist','/mountain-home-va-location-checklist'],['Mountain Home Appointment Prep','/mountain-home-va-appointment-prep']]},
    records:{title:'DD214 or military records path',steps:['Use National Archives or official records channels.','Gather service details before starting the request.','Save confirmation numbers from the official request.'],bring:['Full legal name used during service','Branch','Approximate service dates','Date of birth and mailing address'],official:[['National Archives military service records','https://www.archives.gov/veterans/military-service-records'],['National Archives DD214 page','https://www.archives.gov/personnel-records-center/dd-214']],related:[['Replace DD214','/replace-dd214'],['DD214 Replacement Checklist','/dd214-replacement-checklist']]},
    jobs:{title:'Job, resume or training path',steps:['Pick one or two target job types.','Translate military experience into civilian language.','Use official workforce pages and ask about veteran services.'],bring:['Resume','Work history','Military skills in plain language','Certifications or training records'],official:[['TN American Job Center finder','https://www.tn.gov/workforce/jobs-and-education/job-search1/find-local-american-job-center.html'],['TN Virtual AJC veterans program','https://www.tnvirtualajc.com/veterans-program']],related:[['Veteran job help','/veteran-job-help-east-tennessee'],['Veteran Job Search Starter Kit','/veteran-job-search-starter-kit'],['American Job Center guide','/american-job-center-east-tennessee-veterans']]},
    legal:{title:'Legal aid or court deadline path',steps:['Write down every deadline and court date.','Use official legal aid or a licensed attorney for legal questions.','Ask what documents to bring before sending anything.'],bring:['Court date or notice date','County','Letters or papers if official legal help asks for them','Short timeline'],official:[['Legal Aid of East Tennessee','https://laet.org/'],['Tennessee legal help directory','https://tn.freelegalanswers.org/OtherHelp']],related:[['Veteran legal aid','/veteran-legal-aid-east-tennessee'],['Legal Aid guide','/legal-aid-east-tennessee-veterans-guide'],['Legal Aid Deadline Checklist','/legal-aid-deadline-checklist']]},
    women:{title:'Women veteran support path',steps:['Start with official VA women veterans resources.','Use the Women Veterans Call Center for routing.','Keep medical and trauma details inside official VA, medical or crisis channels.'],bring:['Safe contact method','County','Appointment questions','Whether VA care is already set up'],official:[['VA Women Veterans Health Care','https://www.womenshealth.va.gov/'],['Women Veterans Call Center','https://www.womenshealth.va.gov/wvcc.asp']],related:[['Women veterans in East Tennessee','/women-veterans-east-tennessee'],['Women Veterans Support Checklist','/women-veterans-official-support-checklist']]},
    caregiver:{title:'Family or caregiver help path',steps:['Write down who needs help and the kind of help needed.','Use Military OneSource or VA caregiver support first.','Use official medical or crisis channels for health or safety issues.'],bring:['Relationship to the veteran','County','Safe contact method','Appointment or deadline notes'],official:[['Military OneSource','https://www.militaryonesource.mil/'],['VA Caregiver Support','https://www.caregiver.va.gov/']],related:[['Military family and caregiver help','/military-family-caregiver-help'],['Family Caregiver Support Checklist','/family-caregiver-support-checklist']]},
    local:{title:'Local office or VSO help path',steps:['Use the official office page or lookup before calling.','Ask whether the office handles your exact issue.','Ask what to bring and whether an appointment is needed.'],bring:['Photo ID','DD214 if available','VA letters if relevant','Short description of the issue'],official:[['TDVS county lookup','https://www.tn.gov/veteran/contact-us/county-veterans-services.html'],['VA accredited representative search','https://www.va.gov/get-help-from-accredited-representative/find-rep/']],related:[['Sevier County VSO guide','/sevier-county-veteran-service-office-guide'],['Knox County VSO guide','/knox-county-veteran-service-office-guide'],['TDVS guide','/tennessee-department-veterans-services-guide'],['County Office Call Script','/county-office-call-script']]},
    unsure:{title:'Not sure path',steps:['Start with the issue that feels most urgent.','Use search or the toolkits hub to narrow the problem.','If an official office cannot help, ask which office handles it.'],bring:['County','Deadline if any','Short description of the problem','Safe callback number if needed'],official:[['VA.gov','https://www.va.gov/'],['TDVS','https://www.tn.gov/veteran.html']],related:[['Toolkits','/toolkits'],['Resources','/resources'],['Search','/search']]}
  };
  function planKey(value){var v=(value||'').toLowerCase();if(v.indexOf('crisis')>-1||v.indexOf('danger')>-1)return 'crisis';if(v.indexOf('homeless')>-1||v.indexOf('housing')>-1)return 'housing';if(v.indexOf('benefits')>-1||v.indexOf('claim')>-1)return 'claim';if(v.indexOf('health')>-1||v.indexOf('mountain')>-1)return 'health';if(v.indexOf('dd214')>-1||v.indexOf('records')>-1)return 'records';if(v.indexOf('job')>-1||v.indexOf('resume')>-1||v.indexOf('training')>-1)return 'jobs';if(v.indexOf('legal')>-1||v.indexOf('court')>-1)return 'legal';if(v.indexOf('women')>-1)return 'women';if(v.indexOf('family')>-1||v.indexOf('caregiver')>-1)return 'caregiver';if(v.indexOf('local')>-1||v.indexOf('vso')>-1)return 'local';return 'unsure';}
  function selected(name){return Array.from(document.querySelectorAll('[name="'+name+'"]:checked')).map(function(i){return i.value;});}
  function links(items){return '<ul class="plain-list">'+items.map(function(i){var external=i[1].indexOf('http')===0;return '<li><a href="'+i[1]+'"'+(external?' target="_blank" rel="noopener noreferrer"':'')+'>'+i[0]+'</a></li>';}).join('')+'</ul>';}
  function renderPlan(plan,answers){var crisis=(answers.urgency==='Immediate danger'||answers.issue==='Crisis or immediate danger')?'<div class="danger-box"><strong>Immediate danger:</strong> Call 911 now. For veteran crisis support, call 988 then press 1 or text 838255. Vols4Vets does not monitor emergencies.</div>':'';return crisis+'<h2>Your starting path</h2><p><strong>'+plan.title+'</strong></p><h2>Three exact next steps</h2><ol>'+plan.steps.map(function(s){return '<li>'+s+'</li>';}).join('')+'</ol><h2>What to bring</h2><ul class="plain-list">'+plan.bring.map(function(s){return '<li>'+s+'</li>';}).join('')+'</ul><h2>What not to send to Vols4Vets</h2><p>Do not send Social Security numbers, claim numbers, DD214s, medical records, legal papers, passwords or private case details to Vols4Vets.</p><h2>Official starting links</h2>'+links(plan.official)+'<h2>Related Vols4Vets pages</h2>'+links(plan.related)+'<div class="tool-actions"><button class="button" type="button" data-print-plan>Print this plan</button><button class="button button-secondary" type="button" data-copy-plan>Copy this plan</button><button class="button button-secondary" type="button" data-save-plan>Save this path on this device</button><button class="button button-secondary" type="button" data-clear-plan>Clear saved path</button></div><p class="small">Saved paths stay in this browser on this device. They are not sent to Vols4Vets.</p><p class="small">This tool gives starting points only. It does not diagnose, file claims, give legal advice, give medical advice or contact any office for you.</p>'}
  function plainText(result){return result.innerText||result.textContent||'';}
  document.addEventListener('DOMContentLoaded',function(){var form=document.querySelector('[data-triage-form]');var result=document.querySelector('[data-triage-result]');if(!form||!result)return;form.innerHTML=questions.map(function(q){return '<fieldset class="question-card"><legend><strong>'+q.label+'</strong></legend><div class="option-grid">'+q.options.map(function(o,i){var type=q.multi?'checkbox':'radio';var checked=!q.multi&&i===0?' checked':'';return '<label><input type="'+type+'" name="'+q.name+'" value="'+o+'"'+checked+'> '+o+'</label>';}).join('')+'</div></fieldset>';}).join('')+'<button class="button" type="submit">Get my next steps</button>';function build(){var answers={issue:selected('issue')[0],location:selected('location')[0],urgency:selected('urgency')[0],ready:selected('ready'),goal:selected('goal')[0]};var plan=plans[planKey(answers.issue)];result.innerHTML=renderPlan(plan,answers);return {answers:answers,key:planKey(answers.issue),html:result.innerHTML,text:plainText(result)};}var saved=localStorage.getItem(STORAGE_KEY);if(saved){try{var old=JSON.parse(saved);result.innerHTML=old.html+'<p class="small"><strong>Saved path restored from this device.</strong></p>';}catch(e){localStorage.removeItem(STORAGE_KEY);}}form.addEventListener('submit',function(e){e.preventDefault();build();});result.addEventListener('click',function(e){if(e.target.matches('[data-print-plan]'))window.print();if(e.target.matches('[data-copy-plan]')&&navigator.clipboard){navigator.clipboard.writeText(plainText(result));e.target.textContent='Copied';}if(e.target.matches('[data-save-plan]')){localStorage.setItem(STORAGE_KEY,JSON.stringify({html:result.innerHTML,text:plainText(result),savedAt:new Date().toISOString()}));e.target.textContent='Saved on this device';}if(e.target.matches('[data-clear-plan]')){localStorage.removeItem(STORAGE_KEY);e.target.textContent='Saved path cleared';}});});
})();
